[build]
builder = "nixpacks"

[phases.setup]
# Đây là các gói hệ thống bot cần để phát nhạc
nixPkgs = ["ffmpeg", "libopus", "libffi"]

[build.nixpacks]
build_cmd = "pip install -r requirements.txt"

[service]
# Dấu ngoặc đơn giúp xử lý tên file có dấu cách
start_command = "python 'am nhac.py'"
